WELCOME : Welcome To COVID Vaccine Tracker

LOGIN_ATTEMPTS_EXCEEDED : Login Attempts Exceeded!!!

SUCCESS_LOGIN : Successfully Logged In...

ADMIN_MSG : Welcome Admin....

EMPLOYEE_MSG : Welcome Employee....

